### ISSUE TITLE
Trouble running Nostlan from the master branch

### ISSUE THREAD

**Issue by creatxrgithub** [quinton-ashley/nostlan#30]
i think that is very difficult to install.

i've done serveral times. and change the node version to lts or latest with 'sudo n'

`sudo apt install libsdl-ttf-gst libsdl-sound-gst libx11-dev libxtst-dev libpng-dev libtool libudev-dev
npm i electron
npm i robotjs
npm rebuild`

now it still has problems:

`nostlan-master/node_modules/robotjs/build/Release/robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 88. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at Object.<anonymous> (/media/creatxr/WORK/…/robotjs/index.js:1)
    at Object.<anonymous> (/media/creatxr/WORK/…robotjs/index.js:38)`

what's the steps that i am missing? thanks.

**Comment by quinton-ashley** [comment]
Please download the "stable" builds of Nostlan from the releases page of this Github instead.

<https://github.com/quinton-ashley/nostlan/releases>

Don't try to run Nostlan directly from the github master branch unless you're a developer.  If you are and you want to do so, let me know and I can explain how to run it.

**Comment by creatxrgithub** [comment]
version nostlan-1.19.1.AppImage

`Error: spawn pcsx2 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by creatxrgithub** [comment]
sometime it exit without any message.

maybe it's better if it only show the roms that i have, and list roms by text not cover.

thanks.

**Comment by quinton-ashley** [comment]
do you have that emulator installed on your computer?

**Comment by creatxrgithub** [comment]
> do you have that emulator installed on your computer?

it's only a front-end? but i 've also installed mame.

**Comment by quinton-ashley** [comment]
you need to install the ps2 emulator to play ps2 games

**Comment by quinton-ashley** [comment]
running from the main branch no longer needs native modules to be built
