### ISSUE TITLE
DS Player download/install crashes the app

### ISSUE THREAD

**Issue by tonywoode** [quinton-ashley/nostlan#57]
Once I got Nostlan on mac up and running, the first thing that I got really interested in was the DS Player integration (which I note you said was preliminary), reminder i'm on macOS intel, trying to download it via nostlan crashes - "Nostlan Crashed :-("

```shell
TypeError: Cannot read properties of null (reading 'withFileTypes')
    at e.readdir (node:electron/js2c/asar_bundle:5:10214)
    at go$readdir (/Applications/nostlan.app/Contents/Resources/app.asar/node_modules/graceful-fs/graceful-fs.js:206:16)
    at Object.readdir (/Applications/nostlan.app/Contents/Resources/app.asar/node_modules/graceful-fs/graceful-fs.js:211:12)
    at copyDir (/Applications/nostlan.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/copy/copy.js:166:6)
    at onDir (/Applications/nostlan.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/copy/copy.js:152:10)
    at /Applications/nostlan.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/copy/copy.js:73:39
    at callback (/Applications/nostlan.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:306:20)
    at node:electron/js2c/asar_bundle:5:461
    at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

there are downloaded files in the ds_player folder however, but trying to launch also crashes Nostlan with the exact same stack trace

**Comment by quinton-ashley** [comment]
hmmm I'm not sure why it's not working. Can you send me a screenshot of the list of files it downloaded?

**Comment by quinton-ashley** [comment]
Huh everything looks right, idk what is going wrong. Does installing webretro or em-fceux work for you?

**Comment by tonywoode** [comment]
nope both produce that identical trace, with em-fceux all that's in its install folder is fxeux.wasm and with webretro I have the path nostlan/jsemu/webretro/ and a great many retroarch-ey files therein

**Comment by quinton-ashley** [comment]
dang! Seems there is a real issue here, I will try to sort it out soon. Thanks for reporting it

**Comment by quinton-ashley** [comment]
I finally fixed this, try out the beta builds
